"""empty message

Revision ID: 0aa0d320cd7c
Revises: 7eeb715d1ff5
Create Date: 2026-03-22 19:18:16.685881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0aa0d320cd7c'
down_revision = '7eeb715d1ff5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('follower',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_from_id', sa.Integer(), nullable=False),
    sa.Column('user_to_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_from_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_to_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('likes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('userName', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('firstJName', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('lastName', sa.String(length=120), nullable=False))
        batch_op.create_unique_constraint(None, ['userName'])
        batch_op.create_unique_constraint(None, ['firstJName'])
        batch_op.create_unique_constraint(None, ['lastName'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('lastName')
        batch_op.drop_column('firstJName')
        batch_op.drop_column('userName')

    op.drop_table('likes')
    op.drop_table('follower')
    # ### end Alembic commands ###
