"""empty message

Revision ID: 4baa8b26978c
Revises: 98204ae25759
Create Date: 2026-03-25 19:59:10.286467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4baa8b26978c'
down_revision = '98204ae25759'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post_collab')
    with op.batch_alter_table('follower', schema=None) as batch_op:
        batch_op.add_column(sa.Column('follower_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('following_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('follower_user_to_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('follower_user_from_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['following_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['follower_id'], ['id'])
        batch_op.drop_column('user_from_id')
        batch_op.drop_column('user_to_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('follower', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_to_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('user_from_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('follower_user_from_id_fkey', 'user', ['user_from_id'], ['id'])
        batch_op.create_foreign_key('follower_user_to_id_fkey', 'user', ['user_to_id'], ['id'])
        batch_op.drop_column('following_id')
        batch_op.drop_column('follower_id')

    op.create_table('post_collab',
    sa.Column('post_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('collab_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['collab_id'], ['user.id'], name='post_collab_collab_id_fkey'),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], name='post_collab_post_id_fkey')
    )
    # ### end Alembic commands ###
