"""empty message

Revision ID: 55c158256838
Revises: 4baa8b26978c
Create Date: 2026-03-25 20:09:57.890112

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55c158256838'
down_revision = '4baa8b26978c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collaborator', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'user', ['user'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collaborator', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user')

    # ### end Alembic commands ###
