"""empty message

Revision ID: 98204ae25759
Revises: 1c086e971864
Create Date: 2026-03-24 12:44:17.013555

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98204ae25759'
down_revision = '1c086e971864'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('like',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('post_collab',
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('collab_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['collab_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], )
    )
    op.drop_table('likes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('likes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('post_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], name='likes_post_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='likes_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='likes_pkey')
    )
    op.drop_table('post_collab')
    op.drop_table('like')
    # ### end Alembic commands ###
