"""empty message

Revision ID: fc13fedb611f
Revises: 0aa0d320cd7c
Create Date: 2026-03-24 11:21:49.049023

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc13fedb611f'
down_revision = '0aa0d320cd7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('user_firstJName_key', type_='unique')
        batch_op.drop_constraint('user_lastName_key', type_='unique')
        batch_op.drop_constraint('user_userName_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint('user_userName_key', ['userName'])
        batch_op.create_unique_constraint('user_lastName_key', ['lastName'])
        batch_op.create_unique_constraint('user_firstJName_key', ['firstJName'])

    # ### end Alembic commands ###
